# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def shared_pods
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Hue'
  pod 'RxTest'
  pod 'RxBlocking'
end

target 'Testing' do
  shared_pods
end

target 'TestingTests' do
  shared_pods
end
